// <auto-generated />
using System;
using AgentSplice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgentSplice.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgentSpliceDbContext))]
    [Migration("20260801234939_InitialMetadataStore")]
    partial class InitialMetadataStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("AgentSplice.Infrastructure.Persistence.Rows.ExchangeMeasurementRow", b =>
                {
                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long?>("EndedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Provenance")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("MeasurementId");

                    b.HasIndex("ExchangeId");

                    b.ToTable("exchange_measurements", (string)null);
                });

            modelBuilder.Entity("AgentSplice.Infrastructure.Persistence.Rows.ExchangeObservationRow", b =>
                {
                    b.Property<Guid>("ObservationId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimestampTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ObservationId");

                    b.HasIndex("ExchangeId", "Sequence")
                        .IsUnique();

                    b.ToTable("exchange_observations", (string)null);
                });

            modelBuilder.Entity("AgentSplice.Infrastructure.Persistence.Rows.ExchangeRow", b =>
                {
                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientModelId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentRetentionState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvironmentSnapshotId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FailureClass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngressProtocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicRequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestSummaryJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionAliasId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolutionSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseSummaryJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeEndpointId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StreamTermination")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StreamedResponse")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Streaming")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamMediaType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamModelId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpstreamRequestId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpstreamStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsageJson")
                        .HasColumnType("TEXT");

                    b.HasKey("ExchangeId");

                    b.HasIndex("RuntimeEndpointId");

                    b.HasIndex("Status");

                    b.HasIndex("StartedAtTicks", "ExchangeId");

                    b.ToTable("exchanges", (string)null);
                });

            modelBuilder.Entity("AgentSplice.Infrastructure.Persistence.Rows.ExchangeMeasurementRow", b =>
                {
                    b.HasOne("AgentSplice.Infrastructure.Persistence.Rows.ExchangeRow", "Exchange")
                        .WithMany("Measurements")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("AgentSplice.Infrastructure.Persistence.Rows.ExchangeObservationRow", b =>
                {
                    b.HasOne("AgentSplice.Infrastructure.Persistence.Rows.ExchangeRow", "Exchange")
                        .WithMany("Observations")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("AgentSplice.Infrastructure.Persistence.Rows.ExchangeRow", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
